#!/bin/bash
PACKAGE=$1
PKGNAME=$2
VERSION=$3
PKGREL=$4
ARCH=$5

echo "Name:           ${PKGNAME}"
echo "Version:        ${VERSION}"
echo "Release:        ${PKGREL}%{?dist}"
echo "BuildArch:      ${ARCH}"
echo "Summary:        S-expression parser for C++"
echo "License:        GPL-3.0-or-later"
echo "Group:          Development/Tools"
echo ""
echo "Source:         ${PKGNAME}-${VERSION}.tar.gz"
echo ""
echo "Url: https://github.com/frefolli/sexpresso"
echo "Requires: gcc, meson"
echo "Prefix: /usr"
echo ""
echo "%description"
echo "S-expression parser for C++"
echo ""
echo "%prep"
echo "%setup"
echo ""
echo "%install"
echo "rm -rf \$RPM_BUILD_ROOT"
echo "mkdir -p \$RPM_BUILD_ROOT"
echo "cp -r usr \$RPM_BUILD_ROOT"
echo ""
echo "%clean"
echo "rm -rf \$RPM_BUILD_ROOT"
echo ""
echo "%files"
find $PACKAGE -type f -printf "/%P\n"
echo ""
echo "%post"
echo "ldconfig"
echo ""
echo "%postun"
echo "ldconfig"
echo ""
echo "%changelog"
echo "* Fri Jul 25 2024 Refolli Francesco <frefolli@campus.unimib.it> - ${VERSION}"
echo "- Created a RPM Package for this Library"
